spring.application.name=opt-llm


spring.ai.ollama.base-url=${OLLAMA_URL}
spring.ai.ollama.chat.model=${MODEL}


spring.datasource.url=${PG_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# For call proxy from class self
spring.main.allow-circular-references=true

# if vector table is necessary to rename
#spring.ai.vectorstore.pgvector.table-name=